---
title: "Untangling the Causal Relationship Between Peace Agreements and Peace"
abstract: "\\dropcap{M}"
author:
  - "Brian Lookabaugh"
  - "University of North Texas"
format: 
  docx:
    toc: false
    reference-doc: (this determines font and formatting)
fontsize: 12pt
bibliography: (placeholder)
linkcolor: "#00853E"
citecolor: "#00853E"
crossref: 
  tbl-prefix: ""
  fig-prefix: ""
  eq-prefix: ""
---

```{r Formatting Setup, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE,
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  comment = ' ',
  fig.align = "center"
)
# Load Required Libraries
pacman::p_load(
  "tidyverse",
  install = FALSE
)
# Set Base Theme Settings for Plotting
theme_set(plot_theme(
  yaxis_size = 32,
  xaxis_size = 32,
  title_size = 40,
  strip_size = 26,
  subtitle_size = 30,
  x_axis_face = "bold",
  y_axis_face = "bold",
  strip_face = "bold",
  axis_text_size = 25,
  plot.background = element_rect(fill = "white", color = "white"),
  axis.text = element_text(size = 20),
  axis.line.x.bottom = element_line(colour = "black"),
  axis.line.y.left = element_line(colour = "black"),
  legend_text_size = 30
))
```

# Introduction

# The Literature on Peace Agreements and Post-Conflict Peace

Overwhelmingly, research on how prior war outcomes effects post-conflict peace has determined that prior war outcomes do, in fact, correlate with post-conflict peace. However, what remains less clear is *what type(s)* of war outcomes matter for preserving post-conflict peace. Earlier findings in this literature suggested that military victories, in which one side of the war ends the conflict by a military defeat of the opponent, are likely to lead to a more peaceful post-conflict environment given that a military defeat results in one side being forced to disarm and demobilize, therefore, reducing the likelihood that the defeated party will have the capacity to challenge the victor once the prior conflict has ended (Wagner 1993). In this sense, wars that are terminated through other means, such as through peace agreements, simply prolong the true termination of war since both parties retain some military capacity to continue conflict when it benefits them, respectively (Luttwak 1999). Licklider (1995) found empirical support for this notion with important caveats. First, according to Licklider (1995) military victories negatively correlate with conflict recurrence *only if the prior conflict was an identity conflict*. Second, military victories were also found to correlate with acts of genocide, despite the "pacifying" effect of potentially reducing the chances of conflict recurrence. Downes (2004) provided a theoretical rationale for why negotiated settlements may be particularly unsuited to resolve *ethnic* conflicts, citing the potential for indivisible issues, the hardening of out-group hostilities, and the near-constant mobilizational capacity of ethnic groups as reasons for these difficulties. Other scholars have argued that further specification is needed to understand why military victories may lead to peace. For example, rebel military victories may lead to increased prospects of post-conflict peace (Toft 2010). After all, rebel organizations (and sentiment for rebel causes) can persist following a government military victory. Rebels have the capacity to temporarily refrain from armed conflict, with the intent of resuming armed conflict at a later point when their mobilizational and military capacity increases. Because of this, it may be expected that the peace generated from a government military victory may be more likely to break down than peace generated from a rebel victory (Quinn et al. 2007). Turning away from the study of *conflict recurrence*, recent work that considers the effect of peace agreements on alternative conceptualizations of post-conflict peace, such as military coups, has demonstrated findings that are not optimistic for proponents of peace agreements (White 2020).

On both theoretical and empirical grounds, the notion that peace agreements are ineffective and likely to break down has been challenged repeatedly. For example, Hartzell (2017) argued that interstate and intrastate conflicts may be so qualitatively different from each other that the application of the bargaining model of war used to theoretically justify the potentially pacifying effects of military victories may be invalid as actors and incentives between the two types of wars may not be interchangeable. Even within the context of the bargaining model of war, many scholars have argued that *the contents of a peace agreement matter* for explaining why certain peace agreements are successful while others are not. Such contents can be manipulated to resolve issues, such as private information and commitment problems, that may lead actors to renege on peace agreements and re-ignite violence (Mattes and Savun 2009, 2010, Joshi et al. 2017). Early works by Hartzell et al. (2001) and Hartzell and Hoddie (2003) emphasized the role of security concerns for warring parties in peace agreements and stressed that the ability to deliver on security concerns is crucial for understanding the success of peace agreements. Although, even the pacifying effects of power-sharing agreements should be viewed with an asterisk as demonstrated by DeRouen et al. (2009) who found that power-sharing agreements that were costlier to the government are more likely to break down. The legitimacy of such security concerns can be bolstered through extensive power-sharing agreements monitored by third-party guarantors.

Indeed, other works have also emphasized the role of third-party actors in impacting the success of peace agreements (Walter 1997, Quinn et al. 2007). DeRouen et al. (2010) argued that third-party intervention is necessary for the success of peace agreements when state capacity in recipient states is low as states with poor governing abilities may be unlikely to effectively implement aspects of a peace agreement. Gurses et al. (2009) found that select types of external intervention and the character of third-party actors may inadvertently lead to the failure of the very peace agreements they mediate. In particular, the authors found that the presence of mediated peace agreements and superpower mediation attempts are correlated with a breakdown in peace while the mediation itself is associated with longer peace duration. External intervention from superpowers, in particular, is problematic given that these actors can leverage their capabilities to pressure domestic actors to reach an agreement that does not address the root causes of conflict and may be primarily beneficial to the aforementioned superpower. These findings lend support to the conclusion of Werner and Yuen (2005) who note that strong peace agreements can be a positive force for post-conflict peace and these agreements can be bolstered with third-party participation. However, when peace agreements are reached "unnaturally", such as through the onset of external intervention from an influential third-party actor, core issues may not be resolved organically and conflict may break out again in the future.

Another sub-set of the peace agreement literature acknowledges that peace agreements are not necessarily implemented over night and that the process of a peace agreement implementation can serve to solidify the peace agreement being worked through. Joshi and Quinn (2015) note that the signing of a comprehensive peace agreement is not a guarantee of the implementation of this very peace agreement and argued that the aggregate implementation of a comprehensive peace agreement serve to normalize political relations between formerly warring actors, aid in addressing commitment problems, and address the core underlying causes of conflict. While Matte's (2018) analysis is primarily focused on territorial interstate disputes rather than intrastate wars, the author's work nonetheless found that partial settlements are correlated with the success of comprehensive dispute resolution. Taken together, articles such as these stress the importance of studying peace agreements through a more dynamic lens.

After decades of research, a consensus on the exact effect of prior war outcomes on post-conflict has not been met. For example, while some pieces find that rebel victories linked to a more peaceful post-conflict environment (Quinn et al. 2007, Mason et al. 2011), recent works have challenged this very finding (Gromes and Ranft 2021). Other recent works, such as White (2020), cast doubt on any notion that peace agreements can serve as a stabilizing force in the post-conflict context by analyzing alternative types of post-conflict destabilization. A potential path forward may lie in the shift towards analyzing the causal impacts of military victories and peace agreements on post-conflict peace. Not only are causal estimates more relevant to scholars and policymakers alike (indeed, both care more about "causes" and "consequences" than "associations" and "correlations"), but obtaining causal estimates may also paint a clearer image of the nature between prior war outcomes and post-conflict peace. The following section describes the state of causal research in the peace agreement literature and discusses how a researcher may be able to make causal inferences from observational data on civil war outcomes and post-conflict peace.

# The State of Causal Research in the Peace Agreements Literature

***Is causal inference possible?/Why Causal Research is Avoided***

***The State and Limitations of Current Causal Research***

***Segue to the Synthetic Control Method***


# The Syntehtic Control Method

# Case Selection and Background

# Results

# Conclusion
